DEBUG = False
MAXIMIZE = False

GAME_NAME = "Umamusume"

WINDOW_LEFT = 0
WINDOW_TOP = 0
WINDOW_RIGHT = 0
WINDOW_BOTTOM = 0
WINDOW_WIDTH = 0
WINDOW_HEIGHT = 0

GAME_LEFT = 0
GAME_RIGHT = 0

MODEL_PATH = "frozen_east_text_detection.pb"
CONF_THRESH = 0.85
NMS_THRESH = 0.3
SCALE = 1.0
INPUT_SIZE = (1280, 1280)
MEAN = (123.68, 116.78, 103.94)
SWAP_RB = True

RELATIVE_POSITIONS = {
    "START_BUTTON": (0.4, 0.89, 0.2, 0.08),
    "BOTTOM_MENU": (0.1375, 0.8, 0.3, 0.05),
    "ENHANCE_BUTTON": (0.1375, 0.8, 0.0525, 0.05),
    "STORY_BUTTON": (0.19, 0.8, 0.0525, 0.05), 
    "HOME_BUTTON": (0.2425, 0.8, 0.091, 0.05),
    "RACE_BUTTON": (0.3335, 0.8, 0.0525, 0.05), 
    "SCOUT_BUTTON": (0.386, 0.8, 0.0525, 0.05),
    "TITLE_BAR": (0.065, 0, 0.1, 0.15),
    "CARRER_BUTTON": (0.31, 0.895, 0.12, 0.05),
    "CLUB_SHOP_BUTTONS": (0.1375, 0.92, 0.12, 0.035),
}

def rel_to_abs(rel):
    x, y, w, h = rel
    abs_x = int(x * WINDOW_WIDTH)
    abs_y = int(y * WINDOW_HEIGHT)
    abs_w = int(w * WINDOW_WIDTH)
    abs_h = int(h * WINDOW_HEIGHT)
    return (abs_x, abs_y, abs_w, abs_h)

START_BUTTON_POS = rel_to_abs(RELATIVE_POSITIONS["START_BUTTON"])
BOTTOM_MENU_POS = rel_to_abs(RELATIVE_POSITIONS["BOTTOM_MENU"])
ENHANCE_BUTTON_POS = rel_to_abs(RELATIVE_POSITIONS["ENHANCE_BUTTON"])
STORY_BUTTON_POS = rel_to_abs(RELATIVE_POSITIONS["STORY_BUTTON"])
HOME_BUTTON_POS = rel_to_abs(RELATIVE_POSITIONS["HOME_BUTTON"])
RACE_BUTTON_POS = rel_to_abs(RELATIVE_POSITIONS["RACE_BUTTON"])
SCOUT_BUTTON_POS = rel_to_abs(RELATIVE_POSITIONS["SCOUT_BUTTON"])
TITLE_BAR_POS = rel_to_abs(RELATIVE_POSITIONS["TITLE_BAR"])
CAREER_BUTTON_POS = rel_to_abs(RELATIVE_POSITIONS["CARRER_BUTTON"])
CLUB_SHOP_BUTTONS = rel_to_abs(RELATIVE_POSITIONS["CLUB_SHOP_BUTTONS"])